### ISSUE TITLE
I am working on a Awesome-Python-HTMX, seeking your feedback

### ISSUE THREAD

**Issue by benjamin-kirkbride** [davidbrochart/jupyspace#7]
A few of us at PyCon this year got together and brainstormed a new Web Stack that we are calling PyHAT (Python, htmx, ASGI, TailwindCSS). The first thing we set out to do is create awesome-python-htmx; a collection of active tools/libraries/projects in that space. Your project seems like a thing to include in a section listing real-world applications using htmx, but I'm having trouble determining what your project actually does :sweat_smile:. I would appreciate a PR (or a comment here :smile:) with a sentence or two explanation of what this project offers, that could be included in it, if you are interested in that.

In addition to that, if you could also participate in PyHAT-stack/awesome-python-htmx#1 that would be greatly appreciated! I would in particular be interested to hear about what your dev experience working with htmx and Python is, what was lacking, etc.

**Comment by davidbrochart** [comment]
Thanks for reaching out @benjamin-kirkbride!
I updated the README with this:
"JupySpace is a web server and client allowing to manage [conda-forge](https://conda-forge.org/) environments from the browser and access them through [JupyterLab](https://jupyterlab.readthedocs.io/)".

**Comment by benjamin-kirkbride** [comment]
Okay awesome! And the project does use htmx? Do you think it would make sense to include as an example of a project using Python and htmx for people looking for inspiration/example projects?

**Comment by davidbrochart** [comment]
Yes, it uses htmx and tailwind. It's not much for now but I intend to make it better, so yes feel free to include it as an example project.

**Comment by benjamin-kirkbride** [comment]
What's the framework? FastAPI?

**Comment by davidbrochart** [comment]
Yes.

**Comment by benjamin-kirkbride** [comment]
it's been added! feel free to drop by https://github.com/PyHAT-stack/awesome-python-htmx/discussions/2

**Comment by davidbrochart** [comment]
Awesome, thanks so much! Great resource, I'm going to dive into it!
